// <auto-generated />
using System;
using System.Collections.Generic;
using CryptoWatcher.Modules.Hyperliquid.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Modules.Hyperliquid.Infrastructure.Migrations
{
    [DbContext(typeof(HyperliquidDbContext))]
    [Migration("20260323124117_FixedCryptoTokenLenght")]
    partial class FixedCryptoTokenLenght
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hyperliquid")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidPositionCashFlow", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidPositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("VaultAddress", "WalletAddress", "Date");

                    b.ToTable("HyperliquidPositionCashFlows", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidPositionDailyPerformance", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("BalanceInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Day");

                    b.ToTable("HyperliquidPositionDailyPerformances", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidSynchronizationState", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("LastProcessedEventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastTransactionHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.HasKey("WalletAddress");

                    b.ToTable("HyperliquidSynchronizationStates", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VaultAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("VaultAddress", "WalletAddress");

                    b.ToTable("HyperliquidVaultPeriod", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("VaultAddress", "WalletAddress");

                    b.ToTable("HyperliquidVaultPositions", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("VaultAddress", "WalletAddress", "Day");

                    b.ToTable("HyperliquidVaultPositionSnapshots", "hyperliquid");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPeriod", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("Periods")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Periods");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
