// <auto-generated />
using System;
using CryptoWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    [Migration("20250914193918_RenameEventTypeToEventMigration")]
    partial class RenameEventTypeToEventMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedAtDay")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CreatedAtDay")
                        .HasColumnType("date");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousScaledAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress");

                    b.ToTable("AavePositions");
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePositionEvent", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.HasKey("PositionId", "Date", "Event");

                    b.ToTable("AavePositionEvent");
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePositionSnapshot", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.HasKey("PositionId", "Day");

                    b.ToTable("AavePositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultEvent", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<decimal>("Usd")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Date");

                    b.HasIndex("WalletAddress");

                    b.ToTable("HyperliquidVaultEvents");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("VaultAddress", "WalletAddress");

                    b.HasIndex("WalletAddress");

                    b.ToTable("HyperliquidVaultPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Day");

                    b.HasIndex("WalletAddress");

                    b.ToTable("HyperliquidVaultPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Shared.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PositionId", "NetworkName");

                    b.HasIndex("NetworkName");

                    b.HasIndex("WalletAddress");

                    b.ToTable("PoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPositionSnapshot", b =>
                {
                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.HasKey("PoolPositionId", "NetworkName", "Day");

                    b.ToTable("PoolPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.UniswapNetwork", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MultiCallAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NftManagerAddress")
                        .IsRequired()
                        .HasMaxLength(266)
                        .HasColumnType("character varying(266)");

                    b.Property<string>("PoolFactoryAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Name");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.ToTable("CronTickers", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockHolder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchParent")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchRunCondition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LockHolder")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchParent");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "ticker");
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePositionEvent", b =>
                {
                    b.HasOne("CryptoWatcher.AaveModule.Entities.AavePosition", null)
                        .WithMany("PositionEvents")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Shared.ValueObjects.TokenInfo", "Token", b1 =>
                        {
                            b1.Property<Guid>("AavePositionEventPositionId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("AavePositionEventDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("AavePositionEventEvent")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AavePositionEventPositionId", "AavePositionEventDate", "AavePositionEventEvent");

                            b1.ToTable("AavePositionEvent");

                            b1.WithOwner()
                                .HasForeignKey("AavePositionEventPositionId", "AavePositionEventDate", "AavePositionEventEvent");
                        });

                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.AaveModule.Entities.AavePosition", null)
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Shared.ValueObjects.TokenInfo", "Token", b1 =>
                        {
                            b1.Property<Guid>("AavePositionSnapshotPositionId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("AavePositionSnapshotDay")
                                .HasColumnType("date");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("AavePositionSnapshotPositionId", "AavePositionSnapshotDay");

                            b1.ToTable("AavePositionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("AavePositionSnapshotPositionId", "AavePositionSnapshotDay");
                        });

                    b.Navigation("Token")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultEvent", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("VaultEvents")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", "Vault")
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vault");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.UniswapNetwork", "UniswapNetwork")
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Shared.ValueObjects.TokenInfo", "Token0", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionPositionId", "PoolPositionNetworkName");

                            b1.ToTable("PoolPositions");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionPositionId", "PoolPositionNetworkName");
                        });

                    b.OwnsOne("CryptoWatcher.Shared.ValueObjects.TokenInfo", "Token1", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionPositionId", "PoolPositionNetworkName");

                            b1.ToTable("PoolPositions");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionPositionId", "PoolPositionNetworkName");
                        });

                    b.Navigation("Token0")
                        .IsRequired();

                    b.Navigation("Token1")
                        .IsRequired();

                    b.Navigation("UniswapNetwork");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPosition", "PoolPosition")
                        .WithMany("PoolPositionSnapshots")
                        .HasForeignKey("PoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.TokenInfoWithFee", "Token0", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionSnapshotPoolPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionSnapshotNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<DateOnly>("PoolPositionSnapshotDay")
                                .HasColumnType("date");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionSnapshotPoolPositionId", "PoolPositionSnapshotNetworkName", "PoolPositionSnapshotDay");

                            b1.ToTable("PoolPositionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionSnapshotPoolPositionId", "PoolPositionSnapshotNetworkName", "PoolPositionSnapshotDay");
                        });

                    b.OwnsOne("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.TokenInfoWithFee", "Token1", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionSnapshotPoolPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionSnapshotNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<DateOnly>("PoolPositionSnapshotDay")
                                .HasColumnType("date");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionSnapshotPoolPositionId", "PoolPositionSnapshotNetworkName", "PoolPositionSnapshotDay");

                            b1.ToTable("PoolPositionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionSnapshotPoolPositionId", "PoolPositionSnapshotNetworkName", "PoolPositionSnapshotDay");
                        });

                    b.Navigation("PoolPosition");

                    b.Navigation("Token0")
                        .IsRequired();

                    b.Navigation("Token1")
                        .IsRequired();
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", "ParentJob")
                        .WithMany("ChildJobs")
                        .HasForeignKey("BatchParent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("CryptoWatcher.AaveModule.Entities.AavePosition", b =>
                {
                    b.Navigation("PositionEvents");

                    b.Navigation("PositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Navigation("PositionSnapshots");

                    b.Navigation("VaultEvents");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.PoolPosition", b =>
                {
                    b.Navigation("PoolPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Infrastructure.Entities.UniswapNetwork", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("ChildJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
