// <auto-generated />
using System;
using System.Collections.Generic;
using System.Numerics;
using CryptoWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    [Migration("20251029171823_AddAavePositionPeriodMigration")]
    partial class AddAavePositionPeriodMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AaveChainConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty<Dictionary<string, object>>("SmartContractAddresses", "CryptoWatcher.Modules.Aave.Entities.AaveChainConfiguration.SmartContractAddresses#AaveAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("PoolAddressesProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("UiPoolDataProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name");

                    b.ToTable("AaveChainConfigurations");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousScaledAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress");

                    b.ToTable("AavePositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotPositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProfitInToken")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty<Dictionary<string, object>>("Token", "CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance.Token#TokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Day", "PositionType", "SnapshotPositionId");

                    b.ToTable("AavePositionDailyPerformances");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionEvent", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Token", "CryptoWatcher.Modules.Aave.Entities.AavePositionEvent.Token#TokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("PositionId", "Date", "Event");

                    b.ToTable("AavePositionEvents");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedAtDay")
                        .HasColumnType("date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartedAtDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PositionId", "ClosedAtDay")
                        .IsUnique()
                        .HasFilter(" \"ClosedAtDay\" IS NULL");

                    b.ToTable("AavePositionPeriod");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.ComplexProperty<Dictionary<string, object>>("Token", "CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot.Token#TokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("PositionId", "Day");

                    b.ToTable("AavePositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidPositionDailyPerformance", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("BalanceInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Day");

                    b.ToTable("HyperliquidPositionDailyPerformances");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultEvent", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<decimal>("Usd")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Date");

                    b.HasIndex("WalletAddress");

                    b.ToTable("HyperliquidVaultEvents");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress");

                    b.HasIndex("WalletAddress");

                    b.ToTable("HyperliquidVaultPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.Property<string>("VaultAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.HasKey("VaultAddress", "WalletAddress", "Day");

                    b.ToTable("HyperliquidVaultPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("BlockscoutUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("LastProcessedBlock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastProcessedBlockUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty<Dictionary<string, object>>("SmartContractAddresses", "CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration.SmartContractAddresses#UniswapAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MultiCall")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PoolFactory")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PositionManager")
                                .IsRequired()
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("StateView")
                                .HasMaxLength(42)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name", "ProtocolVersion");

                    b.ToTable("UniswapChainConfigurations");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TickLower")
                        .HasColumnType("bigint");

                    b.Property<long>("TickUpper")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token0#TokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token1#TokenInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("PositionId", "NetworkName");

                    b.HasIndex("WalletAddress");

                    b.HasIndex("NetworkName", "ProtocolVersion");

                    b.ToTable("UniswapLiquidityPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(66)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token0#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token1#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("PositionId", "NetworkName", "TransactionHash");

                    b.ToTable("UniswapLiquidityPositionCashFlows");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token0#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token1#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("PoolPositionId", "NetworkName", "Day");

                    b.ToTable("UniswapLiquidityPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CumulativeCommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoldValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PositionValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.ComplexProperty<Dictionary<string, object>>("Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token0#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token1#TokenInfoWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("FeeAmount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Day", "NetworkName", "PoolPositionId");

                    b.ToTable("UniswapPositionDailyPerformances");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapSynchronizationState", b =>
                {
                    b.Property<string>("ChainName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UniswapProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<BigInteger>("LastBlockNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("LastTransactionHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<DateTime>("SynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainName", "UniswapProtocolVersion", "WalletAddress");

                    b.HasIndex("WalletAddress");

                    b.ToTable("UniswapSynchronizationState");
                });

            modelBuilder.Entity("CryptoWatcher.Shared.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.ToTable("CronTickers", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockHolder")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "ticker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchParent")
                        .HasColumnType("uuid");

                    b.Property<int?>("BatchRunCondition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LockHolder")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchParent");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "ticker");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionEvent", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("PositionEvents")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("PositionPeriods")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultEvent", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("VaultEvents")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", null)
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("VaultAddress", "WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", null)
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("NetworkName", "ProtocolVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("PositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", "UniswapLiquidityPosition")
                        .WithMany("PoolPositionSnapshots")
                        .HasForeignKey("PoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniswapLiquidityPosition");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapSynchronizationState", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", "ChainConfiguration")
                        .WithMany()
                        .HasForeignKey("ChainName", "UniswapProtocolVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChainConfiguration");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.CronTickerOccurrenceEntity<TickerQ.EntityFrameworkCore.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", "ParentJob")
                        .WithMany("ChildJobs")
                        .HasForeignKey("BatchParent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentJob");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Navigation("PositionEvents");

                    b.Navigation("PositionPeriods");

                    b.Navigation("PositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Hyperliquid.Entities.HyperliquidVaultPosition", b =>
                {
                    b.Navigation("PositionSnapshots");

                    b.Navigation("VaultEvents");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("PoolPositionSnapshots");
                });

            modelBuilder.Entity("TickerQ.EntityFrameworkCore.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("ChildJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
