// <auto-generated />
using System;
using CryptoWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    [Migration("20250608194939_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Entities.PoolPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("SynchronizedAt")
                        .HasColumnType("date");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PositionId", "NetworkName");

                    b.HasIndex("NetworkName");

                    b.HasIndex("WalletAddress");

                    b.ToTable("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.PositionFee", b =>
                {
                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("LiquidityPoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.HasKey("NetworkName", "LiquidityPoolPositionId", "Day");

                    b.HasIndex("LiquidityPoolPositionId", "NetworkName");

                    b.ToTable("LiquidityPoolPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Uniswap.UniswapNetwork", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MultiCallAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NftManagerAddress")
                        .IsRequired()
                        .HasMaxLength(266)
                        .HasColumnType("character varying(266)");

                    b.Property<string>("PoolFactoryAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Name");

                    b.ToTable("Networks");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.PoolPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Entities.Uniswap.UniswapNetwork", "UniswapNetwork")
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Entities.Wallet", "Wallet")
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Entities.TokenInfo", "Token0", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionPositionId", "PoolPositionNetworkName");

                            b1.ToTable("LiquidityPoolPositions");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionPositionId", "PoolPositionNetworkName");
                        });

                    b.OwnsOne("CryptoWatcher.Entities.TokenInfo", "Token1", b1 =>
                        {
                            b1.Property<decimal>("PoolPositionPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<string>("PoolPositionNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PoolPositionPositionId", "PoolPositionNetworkName");

                            b1.ToTable("LiquidityPoolPositions");

                            b1.WithOwner()
                                .HasForeignKey("PoolPositionPositionId", "PoolPositionNetworkName");
                        });

                    b.Navigation("Token0")
                        .IsRequired();

                    b.Navigation("Token1")
                        .IsRequired();

                    b.Navigation("UniswapNetwork");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.PositionFee", b =>
                {
                    b.HasOne("CryptoWatcher.Entities.PoolPosition", "PoolPosition")
                        .WithMany("PositionFees")
                        .HasForeignKey("LiquidityPoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CryptoWatcher.Entities.TokenInfo", "Token0Fee", b1 =>
                        {
                            b1.Property<string>("PositionFeeNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("PositionFeeLiquidityPoolPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<DateOnly>("PositionFeeDay")
                                .HasColumnType("date");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PositionFeeNetworkName", "PositionFeeLiquidityPoolPositionId", "PositionFeeDay");

                            b1.ToTable("LiquidityPoolPositionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("PositionFeeNetworkName", "PositionFeeLiquidityPoolPositionId", "PositionFeeDay");
                        });

                    b.OwnsOne("CryptoWatcher.Entities.TokenInfo", "Token1Fee", b1 =>
                        {
                            b1.Property<string>("PositionFeeNetworkName")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("PositionFeeLiquidityPoolPositionId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<DateOnly>("PositionFeeDay")
                                .HasColumnType("date");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PositionFeeNetworkName", "PositionFeeLiquidityPoolPositionId", "PositionFeeDay");

                            b1.ToTable("LiquidityPoolPositionSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("PositionFeeNetworkName", "PositionFeeLiquidityPoolPositionId", "PositionFeeDay");
                        });

                    b.Navigation("PoolPosition");

                    b.Navigation("Token0Fee")
                        .IsRequired();

                    b.Navigation("Token1Fee")
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Entities.PoolPosition", b =>
                {
                    b.Navigation("PositionFees");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Uniswap.UniswapNetwork", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Entities.Wallet", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });
#pragma warning restore 612, 618
        }
    }
}
