// <auto-generated />
using System;
using System.Collections.Generic;
using System.Numerics;
using CryptoWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    [Migration("20260217171418_MoveAaveHelathFactorToAaveAccountShapshotMigration")]
    partial class MoveAaveHelathFactorToAaveAccountShapshotMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AaveAccountSnapshot", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double>("HealthFactor")
                        .HasColumnType("double precision");

                    b.Property<decimal>("TotalCollateralInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebtInUsd")
                        .HasColumnType("numeric");

                    b.HasKey("WalletAddress", "NetworkName", "Day");

                    b.ToTable("AaveAccountSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AaveChainConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SmartContractAddresses", "CryptoWatcher.Modules.Aave.Entities.AaveChainConfiguration.SmartContractAddresses#AaveAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("PoolAddressesProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("UiPoolDataProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name");

                    b.ToTable("AaveChainConfigurations");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousScaledAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePosition.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("WalletAddress");

                    b.ToTable("AavePositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "Date", "Event");

                    b.ToTable("AavePositionCashFlows");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotPositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProfitInToken")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Day", "PositionType", "SnapshotPositionId");

                    b.ToTable("AavePositionDailyPerformances");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedAtDay")
                        .HasColumnType("date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartedAtDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PositionId", "ClosedAtDay")
                        .IsUnique()
                        .HasFilter(" \"ClosedAtDay\" IS NULL");

                    b.ToTable("AavePositionPeriod");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "Day");

                    b.ToTable("AavePositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("TokenSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("MerklCampaigns");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerklCampaignId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClaimedAmount", "CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow.ClaimedAmount#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MerklCampaignId");

                    b.ToTable("MerklCampaignCashFlows");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignSnapshot", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<Guid>("MerklCampaignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClaimableAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ClaimedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PendingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RewardsAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Day", "MerklCampaignId");

                    b.HasIndex("MerklCampaignId");

                    b.ToTable("MerklCampaignSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarketExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CollateralToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition.CollateralToken#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LoanToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition.LoanToken#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Id");

                    b.ToTable("MorphoMarketPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MorphoMarketPositionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MorphoMarketPositionId");

                    b.ToTable("MorphoMarketPositionCashFlow");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<Guid>("MorphoMarketPositionId")
                        .HasColumnType("uuid");

                    b.Property<double>("HealthFactor")
                        .HasColumnType("double precision");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CollateralToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot.CollateralToken#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LoadToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot.LoadToken#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Day", "MorphoMarketPositionId");

                    b.HasIndex("MorphoMarketPositionId");

                    b.ToTable("MorphoMarketPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("BlockscoutUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("LastProcessedBlock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastProcessedBlockUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SmartContractAddresses", "CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration.SmartContractAddresses#UniswapAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MultiCall")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PoolFactory")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PositionManager")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("StateView")
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name", "ProtocolVersion");

                    b.ToTable("UniswapChainConfigurations");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TickLower")
                        .HasColumnType("bigint");

                    b.Property<long>("TickUpper")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token1#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("PositionId", "NetworkName");

                    b.HasIndex("WalletAddress");

                    b.HasIndex("NetworkName", "ProtocolVersion");

                    b.ToTable("UniswapLiquidityPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token1#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "NetworkName", "TransactionHash", "Event");

                    b.ToTable("UniswapLiquidityPositionCashFlows");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token0#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token1#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PoolPositionId", "NetworkName", "Day");

                    b.ToTable("UniswapLiquidityPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CumulativeCommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoldValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PositionValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token0#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token1#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Day", "NetworkName", "PoolPositionId");

                    b.ToTable("UniswapPositionDailyPerformances");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapSynchronizationState", b =>
                {
                    b.Property<string>("ChainName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("UniswapProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<BigInteger>("LastBlockNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("LastTransactionHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<DateTime>("SynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChainName", "UniswapProtocolVersion", "WalletAddress");

                    b.HasIndex("WalletAddress");

                    b.ToTable("UniswapSynchronizationState");
                });

            modelBuilder.Entity("CryptoWatcher.Shared.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("PositionPeriods")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("MerklCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("MerklCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("MorphoMarketPositionId");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("MorphoMarketPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", null)
                        .WithMany("LiquidityPoolPositions")
                        .HasForeignKey("NetworkName", "ProtocolVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("PositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("PoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapSynchronizationState", b =>
                {
                    b.HasOne("CryptoWatcher.Shared.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletAddress")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", "ChainConfiguration")
                        .WithMany()
                        .HasForeignKey("ChainName", "UniswapProtocolVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChainConfiguration");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("PositionPeriods");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", b =>
                {
                    b.Navigation("LiquidityPoolPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
