// <auto-generated />
using System;
using System.Collections.Generic;
using CryptoWatcher.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Infrastructure.Migrations
{
    [DbContext(typeof(CryptoWatcherDbContext))]
    [Migration("20260323120957_RemoveUniswapMigration")]
    partial class RemoveUniswapMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("TokenSymbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("MerklCampaigns");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MerklCampaignId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ClaimedAmount", "CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow.ClaimedAmount#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MerklCampaignId");

                    b.ToTable("MerklCampaignCashFlows");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignSnapshot", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<Guid>("MerklCampaignId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClaimableAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ClaimedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PendingAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RewardsAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Day", "MerklCampaignId");

                    b.HasIndex("MerklCampaignId");

                    b.ToTable("MerklCampaignSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarketExternalId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CollateralToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition.CollateralToken#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LoanToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition.LoanToken#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Id");

                    b.ToTable("MorphoMarketPositions");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MorphoMarketPositionId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Id");

                    b.HasIndex("MorphoMarketPositionId");

                    b.ToTable("MorphoMarketPositionCashFlow");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<Guid>("MorphoMarketPositionId")
                        .HasColumnType("uuid");

                    b.Property<double>("HealthFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("LiquidationLtv")
                        .HasColumnType("double precision");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CollateralToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot.CollateralToken#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LoadToken", "CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot.LoadToken#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Day", "MorphoMarketPositionId");

                    b.HasIndex("MorphoMarketPositionId");

                    b.ToTable("MorphoMarketPositionSnapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Shared.Entities.Wallet", b =>
                {
                    b.Property<string>("Address")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.HasKey("Address");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("MerklCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaignSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("MerklCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("MorphoMarketPositionId");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("MorphoMarketPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Merkl.Entities.MerklCampaign", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Morpho.Entities.MorphoMarketPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
