// <auto-generated />
using System;
using System.Collections.Generic;
using CryptoWatcher.Modules.Aave.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Modules.Aave.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AaveDbContext))]
    [Migration("20260323124208_FixedCryptoTokenLenght")]
    partial class FixedCryptoTokenLenght
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aave")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AaveAccountSnapshot", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double>("HealthFactor")
                        .HasColumnType("double precision");

                    b.Property<decimal>("TotalCollateralInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalDebtInUsd")
                        .HasColumnType("numeric");

                    b.HasKey("WalletAddress", "NetworkName", "Day");

                    b.ToTable("AaveAccountSnapshots", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PreviousScaledAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePosition.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Id");

                    b.ToTable("AavePositions", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "Date", "Event");

                    b.ToTable("AavePositionCashFlows", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("PositionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SnapshotPositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NetworkName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("ProfitInToken")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionDailyPerformance.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("Day", "PositionType", "SnapshotPositionId");

                    b.ToTable("AavePositionDailyPerformances", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedAtDay")
                        .HasColumnType("date");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartedAtDay")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PositionId", "ClosedAtDay")
                        .IsUnique()
                        .HasFilter(" \"ClosedAtDay\" IS NULL");

                    b.ToTable("AavePositionPeriod", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<double?>("LiquidationLtv")
                        .HasColumnType("double precision");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "Day");

                    b.ToTable("AavePositionSnapshots", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AaveProtocolConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SmartContractAddresses", "CryptoWatcher.Modules.Aave.Entities.AaveProtocolConfiguration.SmartContractAddresses#AaveAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("PoolAddressesProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("UiPoolDataProviderAddress")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name");

                    b.ToTable("AaveProtocolConfigurations", "aave");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionPeriod", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("PositionPeriods")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Aave.Entities.AavePosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Aave.Entities.AavePosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("PositionPeriods");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
