using CryptoWatcher.Exceptions;
using CryptoWatcher.Extensions;
using CryptoWatcher.Shared.ValueObjects;
using CryptoWatcher.ValueObjects;

namespace CryptoWatcher.Modules.Uniswap.Entities;

public class UniswapPositionDailyPerformance
{
    private UniswapPositionDailyPerformance()
    {
    }

    /// <summary>
    /// Represents the unique identifier for a liquidity pool position from NFT manager.
    /// </summary>
    /// <remarks>
    /// This property is used to uniquely identify a specific position within the liquidity pool.
    /// It serves as a key for referencing and managing individual positions across the system.
    /// </remarks>
    public ulong PoolPositionId { get; private set; }

    /// <summary>
    /// Specifies the name of the uniswapNetwork associated with the current configuration or operation.
    /// </summary>
    /// <remarks>
    /// This property is used to identify the uniswapNetwork, such as a blockchain or communication uniswapNetwork,
    /// that the system is interacting with or utilizing for its processes.
    /// </remarks>
    public string NetworkName { get; private set; } = null!;

    /// <summary>
    /// Represents the specific date associated with the daily performance data of a Uniswap liquidity pool position.
    /// </summary>
    /// <remarks>
    /// This property indicates the day for which the performance metrics, such as hold value, current value, and commission,
    /// are calculated. It acts as a reference point for temporal snapshots of the position's activity.
    /// </remarks>
    public DateOnly Day { get; private set; }

    /// <summary>
    /// Represents the value held in a liquidity pool position, denominated in USD.
    /// </summary>
    /// <remarks>
    /// This property calculates and reflects the total financial value associated with a liquidity position
    /// during a specific time period. It is computed based on token values and their prices within
    /// the defined time range of the position's snapshots in the pool.
    /// </remarks>
    public decimal HoldValueInUsd { get; private set; }
    
    public decimal PositionValueInUsd { get; private set; }

    /// <summary>
    /// Represents the current value of a Uniswap liquidity position in USD.
    /// </summary>
    /// <remarks>
    /// This property calculates the net profit or loss in USD for a liquidity position
    /// within a specified time frame. It is used to monitor financial changes and evaluate
    /// the performance of the position in the given period.
    /// </remarks>
    public decimal ProfitInUsd { get; private set; }

    /// <summary>
    /// Represents the amount of commission earned, expressed in USD.
    /// </summary>
    /// <remarks>
    /// This property calculates and provides the total commission generated by the liquidity position
    /// for a given time range. It is useful for assessing the profitability through fees over a specific period.
    /// </remarks>
    public decimal CommissionInUsd { get; private set; }
    
    public decimal CumulativeCommissionInUsd { get; private set; }
    
    public TokenInfoWithFee Token0 { get; private set; }
    
    public TokenInfoWithFee Token1 { get; private set; }

    /// <summary>
    /// Indicates whether the associated liquidity position was actively within the range during the defined period.
    /// </summary>
    /// <remarks>
    /// This property is used to determine if a Uniswap liquidity position fell within the specified range of activity
    /// for a given day. It is primarily evaluated using liquidity position snapshots and can help assess range-bound
    /// performance or strategy adherence.
    /// </remarks>
    public bool IsInRange { get; private set; }

    public static UniswapPositionDailyPerformance Create(UniswapLiquidityPosition position,
        UniswapLiquidityPositionSnapshot previous, UniswapLiquidityPositionSnapshot current)
    {
        if (previous.Day > current.Day)
        {
            throw new DomainException("Previous day cannot be greater than current day");
        }

        return new UniswapPositionDailyPerformance
        {
            PoolPositionId = position.PositionId,
            NetworkName = position.NetworkName,
            PositionValueInUsd = current.TokenSumInUsd(),
            HoldValueInUsd = position.CalculateHoldValueInUsd(previous.Day, current.Day),
            CommissionInUsd = position.CalculateFeeInUsd(previous.Day, current.Day),
            CumulativeCommissionInUsd = position.CalculateLifetimeTotalFeeInUsd(current.Day),
            ProfitInUsd = position.CalculateProfitInUsd(previous.Day, current.Day).Amount,
            Day = current.Day,
            Token0 = current.Token0,
            Token1 = current.Token1,
            IsInRange = current.IsInRange
        };
    }
}