// <auto-generated />
using System;
using System.Collections.Generic;
using CryptoWatcher.Modules.Uniswap.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Modules.Uniswap.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UniswapDbContext))]
    partial class UniswapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("uniswap")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<string>("BlockscoutUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<string>("RpcAuthToken")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RpcUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SmartContractAddresses", "CryptoWatcher.Modules.Uniswap.Entities.UniswapChainConfiguration.SmartContractAddresses#UniswapAddresses", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MultiCall")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PoolFactory")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("PositionManager")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<string>("StateView")
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();
                        });

                    b.HasKey("Name", "ProtocolVersion");

                    b.ToTable("UniswapChainConfigurations", "uniswap");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("integer");

                    b.Property<long>("TickLower")
                        .HasColumnType("bigint");

                    b.Property<long>("TickUpper")
                        .HasColumnType("bigint");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token0#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition.Token1#CryptoToken", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(42)
                                .IsUnicode(false)
                                .HasColumnType("character(42)")
                                .IsFixedLength();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasMaxLength(16)
                                .IsUnicode(false)
                                .HasColumnType("character varying(16)");
                        });

                    b.HasKey("PositionId", "NetworkName");

                    b.ToTable("UniswapLiquidityPositions", "uniswap");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.Property<decimal>("PositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token0#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow.Token1#CryptoTokenStatistic", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PositionId", "NetworkName", "TransactionHash", "Event");

                    b.ToTable("UniswapLiquidityPositionCashFlows", "uniswap");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token0#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot.Token1#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("PoolPositionId", "NetworkName", "Day");

                    b.ToTable("UniswapLiquidityPositionSnapshots", "uniswap");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<string>("NetworkName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("PoolPositionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("CommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CumulativeCommissionInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoldValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PositionValueInUsd")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitInUsd")
                        .HasColumnType("numeric");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token0", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token0#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Token1", "CryptoWatcher.Modules.Uniswap.Entities.UniswapPositionDailyPerformance.Token1#CryptoTokenStatisticWithFee", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("Fee")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceInUsd")
                                .HasColumnType("numeric");
                        });

                    b.HasKey("Day", "NetworkName", "PoolPositionId");

                    b.ToTable("UniswapPositionDailyPerformances", "uniswap");
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionCashFlow", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", null)
                        .WithMany("CashFlows")
                        .HasForeignKey("PositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPositionSnapshot", b =>
                {
                    b.HasOne("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", null)
                        .WithMany("Snapshots")
                        .HasForeignKey("PoolPositionId", "NetworkName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoWatcher.Modules.Uniswap.Entities.UniswapLiquidityPosition", b =>
                {
                    b.Navigation("CashFlows");

                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
