// <auto-generated />
using System;
using System.Numerics;
using CryptoWatcher.Modules.WalletIngestion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoWatcher.Modules.WalletIngestion.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(WalletIngestionDbContext))]
    partial class WalletIngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wallet_ingestion")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoWatcher.Modules.WalletIngestion.Entities.WalletIngestionCheckpoint", b =>
                {
                    b.Property<string>("WalletAddress")
                        .HasMaxLength(42)
                        .IsUnicode(false)
                        .HasColumnType("character(42)")
                        .IsFixedLength();

                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("LastPublishedBlockNumber")
                        .HasColumnType("numeric");

                    b.Property<string>("LastPublishedTransactionHash")
                        .HasMaxLength(66)
                        .IsUnicode(false)
                        .HasColumnType("character(66)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WalletAddress", "ChainId");

                    b.ToTable("WalletIngestionCheckpoints", "wallet_ingestion");
                });
#pragma warning restore 612, 618
        }
    }
}
